<?php

namespace App\Models;

use App\Helpers\ImageHelper;
use Illuminate\Database\Eloquent\Model;

class Package extends Model
{
    protected $fillable = [
        'name','price','direct_income','direct_team_income','upline_income','down_line_income',
        'upline_placement_income','down_line_placement_income','trade_income',
        'company_income','max_limit','min_limit','image','withdraw_limit','fund_limit','product_limit',
        'direct_pool_income',
        'renew_direct_income',
        'renew_direct_team_income',
        'renew_upline_income',
        'renew_down_line_income',
        'renew_upline_placement_income',
        'renew_down_line_placement_income',
        'renew_trade_income',
        'renew_company_income',
        'renew_direct_pool_income',
        'self_rebirth',
        'self_associate',
        'direct_rebirth',
        'direct_associate',
        'renew_self_rebirth',
        'renew_self_associate',
        'renew_direct_rebirth',
        'renew_direct_associate',
        'ten_percent_sale',
        'twenty_percent_sale',
        'thirty_percent_sale',
        'fourty_percent_sale',
        'fifty_percent_sale',
        'starter_package_income',
        'salary_package_income',
        'brand_package_income',
        'company_new_account_income',
        'company_employee_account_income',
        'company_renew_income',
        'fake_price',
        'distribution',
        'flush_income',
        'five_percent_sale',
        'five_percent_sale_limit',
        'ten_percent_sale_limit',
        'fifteen_percent_sale',
        'fifteen_percent_sale_limit',
        'twenty_percent_sale_limit',
        'twenty_five_percent_sale',
        'twenty_five_percent_sale_limit',
        'direct_income_2',
        'direct_income_3',
        'direct_income_4',
        'direct_income_5',
        'self_rebirth',
        'self_loan_limit',
        'renew_direct_income_2',
        'renew_direct_income_3',
        'renew_direct_income_4',
        'renew_direct_income_5',
        'renew_self_loan_limit',
        'renew_all_accounts',
        'all_assoicate',
        'company_assoicate',
        'for_medicine',
        'for_purchase_all',
        'monthly_draw',
        'company_products',
        'renew_starter_package_income',
        'renew_seller_package_income',
        'renew_salary_package_income',
        'renew_brand_package_income',
        'renew_company_new_account_income',
        'renew_company_employee_account_income',
        'renew_company_renew_income',
        'renew_renew_all_accounts',
        'renew_all_assoicate',
        'renew_company_assoicate',
        'renew_for_medicine',
        'renew_for_purchase_all',
        'renew_monthly_draw',
        'renew_company_products',
        'is_associate',
        'is_renew',
        'for_stock',
        'direct_for_stock',
        'direct_loan_limit',
        'health_limit',
        'direct_health_limit',
        'purchase_limit',
        'direct_purchase_limit',
    ];
    public function setImageAttribute($value){
        $this->attributes['image'] = ImageHelper::saveAImage($value,'/package/');
    }
}
